apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obsidian-fns.fullname" . }}-config
  labels:
    {{- include "obsidian-fns.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl .Values.config.configYaml . | nindent 4 }}
