include:
  - project: 'repotea-workspace/kangumi'
    ref: main
    file: '/workflow/generic.yml'

stages:
  - publish
  - deploy

##
# helm
##

# helm charts:
#   stage: publish
#   image: alpine/k8s:1.21.2
#   script:
#     - sh -f .maintain/helm-charts.sh

helm any cors:
  extends:
    - .deploy-helm
  stage: publish
  only:
    changes:
      - helm-charts/any-cors/**/*
  variables:
    BUILD_PATH: helm-charts
    CHART_NAME: any-cors


helm codimd:
  extends:
    - .deploy-helm
  stage: publish
  only:
    changes:
      - helm-charts/codimd/**/*
  variables:
    BUILD_PATH: helm-charts
    CHART_NAME: codimd


##
# docker image
##

# docker image:
#   extends: [.docker]
#   stage: publish
#   script:
#     - sh -f .maintain/docker-image.sh

dockeri any cors:
  extends:
    - .build-image
  stage: publish
  only:
    changes:
      - docker-image/any-cors/**/*
  variables:
    BUILD_PATH: docker-image/any-cors
    DOCKERFILE_PATH: docker-image/any-cors/Dockerfile
    IMAGE_NAME: any-cors
    BUILD_LATEST: 'yes'


dockeri cypress browsers edge:
  extends:
    - .build-image
  stage: publish
  only:
    changes:
      - docker-image/cypress-browsers-edge/**/*
  variables:
    BUILD_PATH: docker-image/cypress-browsers-edge
    DOCKERFILE_PATH: docker-image/cypress-browsers-edge/Dockerfile
    IMAGE_NAME: cypress-browsers-edge
    BUILD_LATEST: 'yes'

dockeri fat android sdk:
  extends:
    - .build-image
  stage: publish
  only:
    changes:
      - docker-image/fat-android-sdk/**/*
  tags:
    - ctb
  variables:
    BUILD_PATH: docker-image/fat-android-sdk
    DOCKERFILE_PATH: docker-image/fat-android-sdk/Dockerfile
    IMAGE_NAME: fat-android-sdk
    BUILD_LATEST: 'yes'

