{{- range $name, $toolchain := .Values.toolchains }}
{{- if and $toolchain.enabled (hasKey $toolchain "sshConfig") }}
{{- $sshConfig := $toolchain.sshConfig }}
{{- range $user, $userFiles := $sshConfig }}
{{- $hasInlineContent := false }}
{{- range $filename, $content := $userFiles }}
{{- if not (kindIs "map" $content) }}
{{- $hasInlineContent = true }}
{{- end }}
{{- end }}
{{- if $hasInlineContent }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tch-{{ $name }}-ssh-{{ $user }}
  labels:
    {{- include "dev-toolchain.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name | quote }}
    dev-toolchain/instance: {{ $name | quote }}
    dev-toolchain/ssh-user: {{ $user | quote }}
type: Opaque
stringData:
  {{- range $filename, $content := $userFiles }}
  {{- if kindIs "string" $content }}
  {{ $filename }}: |
    {{ $content | nindent 4 }}
  {{- else if kindIs "slice" $content }}
  {{ $filename }}: |
    {{- range $content }}
    {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
