{{- range $name, $toolchain := .Values.toolchains }}
{{- if and $toolchain.enabled (hasKey $toolchain "sshConfig") }}
{{- $sshConfig := $toolchain.sshConfig }}
{{- range $user, $userFiles := $sshConfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-toolchain.fullname" $ }}-{{ $name }}-ssh-{{ $user }}
  labels:
    {{- include "dev-toolchain.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name | quote }}
    dev-toolchain/instance: {{ $name | quote }}
    dev-toolchain/ssh-user: {{ $user | quote }}
type: Opaque
stringData:
  {{- range $filename, $content := $userFiles }}
  {{ $filename }}: |
    {{- if kindIs "string" $content }}
    {{ $content | nindent 4 }}
    {{- else if kindIs "slice" $content }}
    {{- range $content }}
    {{ . }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
