{{- range $name, $toolchain := .Values.toolchains }}
{{- if and $toolchain.enabled (hasKey $toolchain "authorizedKeys") (gt (len $toolchain.authorizedKeys) 0) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-toolchain.fullname" $ }}-{{ $name }}-ssh-keys
  labels:
    {{- include "dev-toolchain.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name | quote }}
    dev-toolchain/instance: {{ $name | quote }}
type: Opaque
stringData:
  authorized_keys: |
    {{- range $toolchain.authorizedKeys }}
    {{ . }}
    {{- end }}
{{- end }}
{{- end }}
