#!/usr/bin/env bash
# Common helper functions for dev-toolchain install scripts

set -euo pipefail

# Marker file directory
MARKER_DIR="/root/.dev-tools"
ENV_SCRIPT="/etc/profile.d/99-dev-tools-env.sh"

# Colors for output
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[0;34m'
COLOR_RESET='\033[0m'

# Print functions
print_info() {
  echo -e "${COLOR_BLUE}→${COLOR_RESET} $*"
}

print_success() {
  echo -e "${COLOR_GREEN}✓${COLOR_RESET} $*"
}

print_warning() {
  echo -e "${COLOR_YELLOW}⚠${COLOR_RESET} $*"
}

print_error() {
  echo -e "${COLOR_RED}✗${COLOR_RESET} $*" >&2
}

print_header() {
  echo "=========================================="
  echo "$*"
  echo "=========================================="
}

# Check if tool is already installed by checking actual binaries
# Usage: check_installed "devtools"
# Returns: 0 if installed, 1 otherwise
# Note: This function is kept for backward compatibility but now checks
# actual installation rather than marker files to avoid persistence issues
check_installed() {
  local tool_name="$1"

  # Special handling for meta-packages
  case "${tool_name}" in
    devtools)
      # Check if key system packages are installed
      command -v autoconf &>/dev/null && command -v automake &>/dev/null
      return $?
      ;;
    *)
      # For other tools, always return 1 (not installed)
      # This ensures tools from Homebrew are checked by Homebrew itself
      return 1
      ;;
  esac
}

# Mark tool as installed (now a no-op, kept for backward compatibility)
# Usage: mark_installed "nodejs" "22.15.1"
mark_installed() {
  local tool_name="$1"
  local version="${2:-unknown}"

  # No longer create marker files to avoid persistence issues
  # Installation state is determined by actual binary existence
  print_success "✓ ${tool_name} ${version} installed"
}

# Ensure environment block exists in env script (idempotent)
# Usage: ensure_env_block "marker_comment" "env_block_content"
# Example: ensure_env_block "# Go Programming Language" "export GOROOT=/opt/golang/current"
ensure_env_block() {
  local marker="$1"
  local block="$2"

  # Create env script if it doesn't exist
  if [ ! -f "${ENV_SCRIPT}" ]; then
    cat > "${ENV_SCRIPT}" << 'EOF'
#!/bin/bash
# Dev Tools Environment Configuration
# Auto-generated by dev-toolchain install scripts

EOF
    chmod +x "${ENV_SCRIPT}"
  fi

  # Check if marker already exists
  if grep -qF "${marker}" "${ENV_SCRIPT}" 2>/dev/null; then
    return 0
  fi

  # Append the block
  echo "" >> "${ENV_SCRIPT}"
  echo "${block}" >> "${ENV_SCRIPT}"
}



# Create version directory structure and symlink
# Usage: setup_version_dir "/opt/flutter" "3.35.1"
# Creates: /opt/flutter/versions/3.35.1/
#          /opt/flutter/current -> versions/3.35.1
setup_version_dir() {
  local base_dir="$1"
  local version="$2"
  local version_dir="${base_dir}/versions/${version}"
  local current_link="${base_dir}/current"

  mkdir -p "${version_dir}"

  # Update current symlink
  ln -sfn "versions/${version}" "${current_link}"

  echo "${version_dir}"
}

# Get current version from symlink
# Usage: get_current_version "/opt/flutter"
# Returns: version string or empty if not found
get_current_version() {
  local base_dir="$1"
  local current_link="${base_dir}/current"

  if [ ! -L "${current_link}" ]; then
    echo ""
    return
  fi

  local target
  target=$(readlink "${current_link}")
  echo "${target}" | sed 's|versions/||'
}
