#!/usr/bin/env bash
# Common helper functions for dev-toolchain install scripts

set -euo pipefail

# Marker file directory
MARKER_DIR="/root/.dev-tools"
ENV_SCRIPT="/etc/profile.d/99-dev-tools-env.sh"

# Colors for output
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[0;34m'
COLOR_RESET='\033[0m'

# Print functions
print_info() {
  echo -e "${COLOR_BLUE}→${COLOR_RESET} $*"
}

print_success() {
  echo -e "${COLOR_GREEN}✓${COLOR_RESET} $*"
}

print_warning() {
  echo -e "${COLOR_YELLOW}⚠${COLOR_RESET} $*"
}

print_error() {
  echo -e "${COLOR_RED}✗${COLOR_RESET} $*" >&2
}

print_header() {
  echo "=========================================="
  echo "$*"
  echo "=========================================="
}

# Check if tool is already installed via marker file
# Usage: check_installed "nodejs" "22.15.1"
# Returns: 0 if installed with same version, 1 otherwise
check_installed() {
  local tool_name="$1"
  local expected_version="${2:-}"
  local marker_file="${MARKER_DIR}/${tool_name}.installed"

  if [ ! -f "${marker_file}" ]; then
    return 1
  fi

  if [ -z "${expected_version}" ]; then
    print_success "${tool_name} is already installed"
    return 0
  fi

  local installed_version
  installed_version=$(cat "${marker_file}" 2>/dev/null || echo "")

  if [ "${installed_version}" = "${expected_version}" ]; then
    print_success "${tool_name} ${expected_version} is already installed"
    return 0
  else
    print_info "${tool_name} is installed but version mismatch (installed: ${installed_version}, expected: ${expected_version})"
    return 1
  fi
}

# Mark tool as installed
# Usage: mark_installed "nodejs" "22.15.1"
mark_installed() {
  local tool_name="$1"
  local version="${2:-unknown}"
  local marker_file="${MARKER_DIR}/${tool_name}.installed"

  mkdir -p "${MARKER_DIR}"
  echo "${version}" > "${marker_file}"
  print_success "Marked ${tool_name} ${version} as installed"
}

# Append line to env script if not already present
# Usage: append_to_env 'export PATH="/opt/flutter/current/bin:$PATH"'
append_to_env() {
  local line="$1"

  # Create env script if it doesn't exist
  if [ ! -f "${ENV_SCRIPT}" ]; then
    cat > "${ENV_SCRIPT}" << 'EOF'
#!/bin/bash
# Dev Tools Environment Configuration
# Auto-generated by dev-toolchain install scripts

EOF
    chmod +x "${ENV_SCRIPT}"
  fi

  # Check if line already exists
  if grep -qF "${line}" "${ENV_SCRIPT}" 2>/dev/null; then
    return 0
  fi

  echo "${line}" >> "${ENV_SCRIPT}"
}

# Create version directory structure and symlink
# Usage: setup_version_dir "/opt/flutter" "3.35.1"
# Creates: /opt/flutter/versions/3.35.1/
#          /opt/flutter/current -> versions/3.35.1
setup_version_dir() {
  local base_dir="$1"
  local version="$2"
  local version_dir="${base_dir}/versions/${version}"
  local current_link="${base_dir}/current"

  mkdir -p "${version_dir}"

  # Update current symlink
  ln -sfn "versions/${version}" "${current_link}"

  echo "${version_dir}"
}

# Get current version from symlink
# Usage: get_current_version "/opt/flutter"
# Returns: version string or empty if not found
get_current_version() {
  local base_dir="$1"
  local current_link="${base_dir}/current"

  if [ ! -L "${current_link}" ]; then
    echo ""
    return
  fi

  local target
  target=$(readlink "${current_link}")
  echo "${target}" | sed 's|versions/||'
}
