#!/usr/bin/env bash

set -euo pipefail

ENV_SCRIPT="/etc/profile.d/99-dev-tools-env.sh"

# Create env script if it doesn't exist
if [ ! -f "${ENV_SCRIPT}" ]; then
  cat > "${ENV_SCRIPT}" << 'EOF'
#!/bin/bash
# Dev Tools Environment Configuration
# Auto-generated by dev-toolchain install scripts

EOF
  chmod +x "${ENV_SCRIPT}"
fi

# Set custom hostname in prompt if CUSTOM_HOSTNAME env var is set
# This is needed in hostNetwork mode where pod hostname is the node hostname
# We use PS1 to display the desired hostname instead
if [ -n "${CUSTOM_HOSTNAME:-}" ]; then
  # Check if PS1 customization is already in the file
  if ! grep -qF "export CUSTOM_HOSTNAME=" "${ENV_SCRIPT}" 2>/dev/null; then
    cat >> "${ENV_SCRIPT}" << EOF

# Custom Hostname for Prompt
export CUSTOM_HOSTNAME="${CUSTOM_HOSTNAME}"
export PS1='\${debian_chroot:+(\$debian_chroot)}\u@\${CUSTOM_HOSTNAME}:\w\$ '
EOF
  fi
fi

# Export DOCKER_HOST if set (from Kubernetes env vars)
if [ -n "${DOCKER_HOST:-}" ]; then
  # Check if DOCKER_HOST is already in the file
  if ! grep -qF "export DOCKER_HOST=" "${ENV_SCRIPT}" 2>/dev/null; then
    cat >> "${ENV_SCRIPT}" << EOF

# Docker Client Configuration
export DOCKER_HOST="${DOCKER_HOST}"
EOF
  fi
fi
