name: 'Gitops deploy action'
description: "Update YAML in gitops repo using fjogeleit/yaml-update-action"

inputs:
  repository:
    description: 'GitOps repository to update'
    required: false
    default: 'repotea-workflow/gitops'
  deploy_key:
    description: 'SSH deploy key for repository'
    required: true
  changes:
    description: 'JSON for multi-file/multi-value changes'
    required: false
  valueFile:
    description: 'Path to YAML file to update (relative to repo root)'
    required: false
  propertyPath:
    description: 'Property path to update'
    required: false
  value:
    description: 'Value to set'
    required: false

  source_repository:
    description: 'source repository path, e.g. prtmax/endfather'
    required: false
  commit_message:
    description: 'commit message'
    required: false
    default: '__origin__/.github/message.txt'
  ac_git_ref:
    description: 'action context: git ref'
    required: false
    default: '__origin__/.github/ref.txt'
  commit_id:
    description: 'action context: commit id'
    required: false
    default: '__origin__/.github/commit.txt'

  argocd_server:
    description: 'ArgoCD server URL'
    required: false
  argocd_username:
    description: 'ArgoCD username'
    required: false
  argocd_api_token:
    description: 'ArgoCD API token'
    required: false
  app_name:
    description: 'ArgoCD application name to sync after commit'
    required: false
  wait_health:
    description: 'Wait for application to be healthy after sync'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Check if gitops repo already exists
      id: check-gitops-repo
      shell: bash
      run: |
        if [ -d "gitops-repo" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "GitOps repo directory already exists, skipping checkout"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "GitOps repo directory does not exist, will checkout"
        fi

    - name: Checkout gitops repo
      if: steps.check-gitops-repo.outputs.exists == 'false'
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        ssh-key: ${{ inputs.deploy_key }}
        path: gitops-repo
        fetch-depth: 0

    - name: Update YAML using fjogeleit/yaml-update-action
      uses: fjogeleit/yaml-update-action@main
      with:
        workDir: gitops-repo
        commitChange: 'false'
        changes: ${{ inputs.changes }}
        valueFile: ${{ inputs.valueFile }}
        propertyPath: ${{ inputs.propertyPath }}
        value: ${{ inputs.value }}

    - name: Generate message
      id: generate-commit-message
      shell: bash
      run: |
        INPUT_SOURCE_REPOSITORY="${{ inputs.source_repository }}"
        INPUT_COMMIT_MESSAGE="${{ inputs.commit_message }}"
        INPUT_AC_GIT_REF="${{ inputs.ac_git_ref }}"
        INPUT_COMMIT_ID="${{ inputs.commit_id }}"

        # read commit_message
        if [ -f "${INPUT_COMMIT_MESSAGE}" ]; then
          COMMIT_MSG=$(cat ${INPUT_COMMIT_MESSAGE})
        else
          COMMIT_MSG="${INPUT_COMMIT_MESSAGE}"
        fi

        # read ac_git_ref
        if [ -f "${INPUT_AC_GIT_REF}" ]; then
          AC_GIT_REF=$(cat ${INPUT_AC_GIT_REF})
        else
          AC_GIT_REF="${INPUT_AC_GIT_REF}"
        fi

        # read commit_id
        if [ -f "${INPUT_COMMIT_ID}" ]; then
          COMMIT_ID=$(cat ${INPUT_COMMIT_ID})
        else
          COMMIT_ID="${INPUT_COMMIT_ID}"
        fi

        # read commit_date if exists
        COMMIT_DATE=""
        if [ -f "__origin__/.github/date.txt" ]; then
          COMMIT_DATE=$(cat __origin__/.github/date.txt)
        fi

        # read author if exists
        COMMIT_AUTHOR=""
        if [ -f "__origin__/.github/author.txt" ]; then
          COMMIT_AUTHOR=$(cat __origin__/.github/author.txt)
        fi

        # read source_repository, use input first, if not set use repository.txt
        if [ -n "${INPUT_SOURCE_REPOSITORY}" ]; then
          SOURCE_REPOSITORY="${INPUT_SOURCE_REPOSITORY}"
        elif [ -f "__origin__/.github/repository.txt" ]; then
          SOURCE_REPOSITORY=$(cat __origin__/.github/repository.txt)
        else
          SOURCE_REPOSITORY="${{ github.repository }}"
        fi

        # build commit links
        COMMIT_LINKS="    - https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
        if [ -n "${AC_GIT_REF}" ]; then
          COMMIT_LINKS="${COMMIT_LINKS}"$'\n'"    - https://github.com/${SOURCE_REPOSITORY}/tree/${AC_GIT_REF}"
        fi
        if [ -n "${COMMIT_ID}" ]; then
          COMMIT_LINKS="${COMMIT_LINKS}"$'\n'"    - https://github.com/${SOURCE_REPOSITORY}/commit/${COMMIT_ID}"
        fi

        # extract first line of commit message as subject
        COMMIT_MSG_SUBJECT=$(echo "${COMMIT_MSG}" | head -n 1 | cut -c 1-60)
        if [ ${#COMMIT_MSG_SUBJECT} -ge 60 ]; then
          COMMIT_MSG_SUBJECT="${COMMIT_MSG_SUBJECT}..."
        fi

        {
          echo "message<<EOF"
          echo "[${SOURCE_REPOSITORY}] ${AC_GIT_REF} :: ${COMMIT_MSG_SUBJECT}"
          echo ""
          echo "--- Commit Message ---"
          echo "${COMMIT_MSG}"
          echo ""
          echo "--- Actions Context ---"
          echo "* Repository: https://github.com/${SOURCE_REPOSITORY}"
          echo "* Git Ref: ${AC_GIT_REF}"
          if [ -n "${COMMIT_AUTHOR}" ]; then
            echo "* Author: ${COMMIT_AUTHOR}"
          fi
          if [ -n "${COMMIT_DATE}" ]; then
            echo "* Commit Date: ${COMMIT_DATE}"
          fi
          echo "* Build started at: ${{ github.event.head_commit.timestamp }}"
          echo "* Source: ${{ github.event_name }}"
          echo "* Workflows: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "* Commits:"
          echo "${COMMIT_LINKS}"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"


    - uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        # committer_name: GitHub Actions
        # committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        default_author: github_actions
        commit: --signoff
        cwd: './gitops-repo'
        message: ${{ steps.generate-commit-message.outputs.message }}
        push: true

    - name: Setup ArgoCD CLI
      if: inputs.argocd_server != '' && inputs.argocd_api_token != '' && inputs.app_name != ''
      uses: imajeetyadav/argocd-cli@v1

    - name: Sync ArgoCD Application
      if: inputs.argocd_server != '' && inputs.argocd_api_token != '' && inputs.app_name != ''
      shell: bash
      env:
        ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_api_token }}
      run: |
        echo "Syncing ArgoCD application: ${{ inputs.app_name }}"
        argocd --server=${{ inputs.argocd_server }} app sync ${{ inputs.app_name }}

        if [ "${{ inputs.wait_health }}" = "true" ]; then
          echo "Waiting for application to be healthy..."
          argocd --server=${{ inputs.argocd_server }} app wait ${{ inputs.app_name }} --health --timeout 300
        else
          echo "Skipping health check (wait_health is disabled)"
        fi
