apiVersion: v2
appVersion: v2.6.0
description: Meet Plane. An Enterprise software development tool to manage issues,
  sprints, and product roadmaps with peace of mind.
home: https://plane.so/
icon: https://plane.so/favicon/favicon-32x32.png
name: plane-enterprise-helm
sources:
- https://github.com/makeplane/plane-ee
type: application
version: 0.1.1
