#!/usr/bin/env bash
# Common helper functions for dev-toolchain install scripts
# Simplified version for custom tools (most tools now use Homebrew)

set -euo pipefail

# Environment script
ENV_SCRIPT="/etc/profile.d/99-dev-tools-env.sh"

# Colors for output
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[0;34m'
COLOR_RESET='\033[0m'

# Print functions
print_info() {
  echo -e "${COLOR_BLUE}→${COLOR_RESET} $*"
}

print_success() {
  echo -e "${COLOR_GREEN}✓${COLOR_RESET} $*"
}

print_warning() {
  echo -e "${COLOR_YELLOW}⚠${COLOR_RESET} $*"
}

print_error() {
  echo -e "${COLOR_RED}✗${COLOR_RESET} $*" >&2
}

print_header() {
  echo "=========================================="
  echo "$*"
  echo "=========================================="
}

# Ensure environment block exists in env script (idempotent)
# Usage: ensure_env_block "marker_comment" "env_block_content"
# Example: ensure_env_block "# HarmonyOS Tools" "export PATH=/opt/harmony/current/bin:\$PATH"
ensure_env_block() {
  local marker="$1"
  local block="$2"

  # Create env script if it doesn't exist
  if [ ! -f "${ENV_SCRIPT}" ]; then
    cat > "${ENV_SCRIPT}" << 'EOF'
#!/bin/bash
# Dev Tools Environment Configuration
# Auto-generated by dev-toolchain install scripts

EOF
    chmod +x "${ENV_SCRIPT}"
  fi

  # Check if marker already exists
  if grep -qF "${marker}" "${ENV_SCRIPT}" 2>/dev/null; then
    return 0
  fi

  # Append the block
  echo "" >> "${ENV_SCRIPT}"
  echo "${block}" >> "${ENV_SCRIPT}"
}
