name: 'Trigger Dynamic Actions'
description: 'Trigger dynamic actions to run you CI'
inputs:
  dot_github:
    description: 'The path for .github'
    required: false
    default: '.github'
  git_email:
    description: 'Git email'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  git_name:
    description: 'Git name'
    required: false
    default: 'github-actions[bot]'
  ssh_key:
    description: 'SSH private key'
    required: true
  dyn_owner:
    description: 'dynamic actions repo owner'
    required: false
    default: '0xfe10'
runs:
  using: "composite"
  steps:
    - name: Tag
      uses: olegtarasov/get-tag@v2.1
    - name: Sha
      uses: benjlevesque/short-sha@v3.0
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ inputs.ssh_key }}
        ssh-host: github.com
    - name: Expose git commit data
      uses: jcputney/git-commit-data-action@v2
    - name: Trigger dynamic actions
      shell: bash
      run: |
        INPUT_DOT_GITHUB=${{ inputs.dot_github }}
        INPUT_GIT_EMAIL=${{ inputs.git_email }}
        INPUT_GIT_NAME=${{ inputs.git_name }}

        # repository is the full github repo path, e.g. prtmax/endfather
        REPOSITORY=${{ github.repository }}
        # project_name is just the repo name, e.g. endfather (used for git tag)
        PROJECT_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)

        T_BRANCH=${{ github.repository }}

        git clone git@github.com:${{ inputs.dyn_owner }}/dynamic-actions.git
        cd dynamic-actions
        git fetch
        git checkout -b $T_BRANCH origin/$T_BRANCH || (git branch $T_BRANCH && git checkout $T_BRANCH)
        git pull || true

        # prepare changes

        rm -rf .github
        mkdir -p .github

        # only copy dyn-workflows as workflows, ignore other directories like instructions
        if [ -d "../$INPUT_DOT_GITHUB/dyn-workflows" ]; then
          mv ../$INPUT_DOT_GITHUB/dyn-workflows .github/workflows
        else
          echo 'not found dyn-workflows dir'
          exit 1
        fi

        date -u +"%Y-%m-%dT%H:%M:%SZ" > .github/date.txt

        REPO_BRANCH=${{ steps.extract_branch.outputs.branch }}
        REPO_TAG=${{ env.GIT_TAG_NAME }}
        COMMIT_SHA=${{ env.SHA }}

        if [ -n "${REPO_TAG}" ]; then
          echo ${REPO_TAG} > .github/tag.txt
          echo ${REPO_TAG} > .github/ref.txt
          rm -rf .github/branch.txt || true
        else
          echo ${REPO_BRANCH} > .github/branch.txt
          echo ${REPO_BRANCH} > .github/ref.txt
          rm -rf .github/tag.txt || true
        fi

        LATEST_COMMIT_LOG="${{ github.event.head_commit.message }}"
        COMMIT_MSG=${COMMIT_MSG:-${LATEST_COMMIT_LOG}}
        COMMIT_MSG=${COMMIT_MSG:-${GIT_COMMIT_MESSAGE}}

        echo "${COMMIT_MSG}" > .github/message.txt
        echo "${COMMIT_SHA}" > .github/commit.txt
        echo "${REPOSITORY}" > .github/repository.txt

        # write author info (use @username format)
        AUTHORS_JSON='${{ toJSON(github.event.commits.*.author.username) }}'
        if [ "${AUTHORS_JSON}" != "null" ] && [ "${AUTHORS_JSON}" != "[]" ] && [ -n "${AUTHORS_JSON}" ]; then
          echo "${AUTHORS_JSON}" | jq -r '.[] | "@\(.)"' 2>/dev/null | sort -u > .github/author.txt
        fi
        # fallback to head_commit author username if author.txt is empty
        if [ ! -s .github/author.txt ]; then
          HEAD_AUTHOR_USERNAME="${{ github.event.head_commit.author.username }}"
          if [ -n "${HEAD_AUTHOR_USERNAME}" ]; then
            echo "@${HEAD_AUTHOR_USERNAME}" > .github/author.txt
          fi
        fi
        # fallback to actor if still empty
        if [ ! -s .github/author.txt ]; then
          echo "@${{ github.actor }}" > .github/author.txt
        fi

        # push
        git config user.name "${INPUT_GIT_NAME}"
        git config user.email "${INPUT_GIT_EMAIL}"

        git status
        git add .

        # Write commit message to temp file to handle special characters safely
        printf "[%s]: %s" "${T_BRANCH}" "${COMMIT_MSG}" > /tmp/commit_message.txt
        git commit -F /tmp/commit_message.txt
        rm /tmp/commit_message.txt

        git push origin $T_BRANCH

        if [ -z "${REPO_TAG}" ]; then
          echo "This is pushed a branch (${REPO_BRANCH}). completed to push Github Actions."
          exit 0
        fi

        TAG_NAME=${REPO_TAG}-${PROJECT_NAME}
        git tag -d ${TAG_NAME} || true
        git push origin :${TAG_NAME} || true

        git tag ${TAG_NAME}
        git push origin ${TAG_NAME}
