{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lanhu-mcp.dataClaimName" . }}
  labels:
    {{- include "lanhu-mcp.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
---
{{- end }}
{{- if and .Values.persistence.logs.enabled (not .Values.persistence.logs.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lanhu-mcp.logsClaimName" . }}
  labels:
    {{- include "lanhu-mcp.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  {{- if .Values.persistence.logs.storageClass }}
  storageClassName: {{ .Values.persistence.logs.storageClass | quote }}
  {{- end }}
{{- end }}
