{{- if and .Values.persistence.shared.enabled (not .Values.persistence.shared.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lanhu-mcp.sharedClaimName" . }}
  labels:
    {{- include "lanhu-mcp.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.shared.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.shared.size }}
  {{- if .Values.persistence.shared.storageClass }}
  storageClassName: {{ .Values.persistence.shared.storageClass | quote }}
  {{- end }}
{{- end }}
