apiVersion: v2
name: any-tunnel-helm
description: Unified proxy service supporting TCP, HTTP, SOCKS, and more with nginx, gost, etc.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.2

# This is the version number of the application being deployed.
appVersion: "1.0.0"
