dependencies:
  - name: postgresql
    version: ~8.6.10
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: mariadb
    version: ~7.3.16
    condition: mariadb.enabled
    repository: https://charts.bitnami.com/bitnami

