name: Publish Docker Image

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:

  build-stage-one:
    name: Build Stage One
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - package: gotenberg
            context: docker-image/gotenberg
            build-args: ""
          - package: node-liveness-probe
            context: docker-image/node-liveness-probe
            build-args: |
              NODE_LIVENESS_PROBE_VERSION=v0.6.1
          - package: terraform
            context: docker-image/terraform
            build-args: |
              TERRAFORM_VERSION=1.4.6
              TERRAFORM_BACKEND_GIT_VERSION=v0.1.8
          - package: k8ops
            context: docker-image/k8ops
            build-args: |
              KUBECTL_VERSION=1.33.3
              HELMFILE_VERSION=1.1.3-3.18.4
              KUSTOMIZE_VERSION=v5.7.1
              HELM_VERSION=v3.18.0
              HELM_DIFF_VERSION=v3.1.3
              ARGOCD_VERSION=v3.1.0

          # - package: fat-android-sdk
          #   context: docker-image/fat-android-sdk
          #   build-args: ""
          # - package: artelad
          #   context: docker-image/artelad
          #   build-args: ""
          # - package: fuel
          #   context: docker-image/fuel
          #   build-args: ""
          # - package: nubit
          #   context: docker-image/nubit
          #   build-args: ""
          - package: harmonytools
            context: docker-image/harmonytools
            build-args: ""
    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.context }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.package }}:sha-${{ env.SHA }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.package }}:latest
          build-args: ${{ matrix.build-args }}

  build-stage-two:
    name: Build Stage Two
    runs-on: ubuntu-latest
    needs:
      - build-stage-one
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - package: appbox
            context: docker-image/appbox
            build-args: |
              DOCKER_COMPOSE_VERSION=2.39.2
              S6_OVERLAY_VERSION=3.2.1.0
          - package: dev-toolchain
            context: docker-image/dev-toolchain
            build-args: |
              FLUTTER_VERSION=3.35.1
              NVM_VERSION=0.40.3
              NODE_VERSION=22.15.1
              DOCKER_COMPOSE_VERSION=2.39.2
              S6_OVERLAY_VERSION=3.2.1.0
              GCM_VERSION=2.6.1
              HELM_DIFF_VERSION=v3.1.3
    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.context }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.package }}:sha-${{ env.SHA }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.package }}:latest
          build-args: ${{ matrix.build-args }}

