name: Clone Repository Workflow

on:
  push:
  workflow_dispatch:

jobs:

  clone-via-http:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

# # todo:  fix this
#      - name: Clone repository
#        uses: ./clone-any
#        with:
#          platform: github
#          repository: fewensa/actions
#          target: actions-group
#
#      - name: Access cloned repository content
#        run: ls -l actions-group

