name: Release helm chart

on:
  push:
    branches: [main]
  # workflow_dispatch:

jobs:
  release-helm-chart:
    name: Release helm chart
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - package: any-cors
            path: helm-charts/any-cors
    steps:
      - uses: actions/checkout@v5

      - name: Get Chart Version
        id: chart_version
        run: |
          version=$(yq eval '.version' ${{ matrix.path }}/Chart.yaml)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: ${{ matrix.package }}
          repository: ${{ github.repository }}
          tag: ${{ steps.chart_version.outputs.version }}
          path: ${{ matrix.path }}
          registry: ghcr.io
          registry_username: "0xfe10"
          registry_password: ${{ github.token }}
          update_dependencies: "true" # Defaults to false

